Dir::Etc::parts "/opt/sprowt-apt/conf.d";
Dir::Etc::main "/dev/null";
Dir::Etc::sourcelist "/dev/null";
Dir::Etc::sourceparts "/opt/sprowt-apt";
Dir::Cache "/opt/sprowt-apt/cache";
Dir::State::lists "/opt/sprowt-apt/lists";
Dir::Log::Terminal "";
APT::Sandbox::User "root";
Acquire::Retries "2";
Acquire::http::Timeout "30";
Acquire::https::Timeout "30";
APT::Update::Error-Mode "any";
DPkg::Options { "--force-confold"; };
